apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/dignacio2015/node-http-watch-pipeline-activity:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/dignacio2015/node-http-watch-pipeline-activity:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: node-http-watch-pipeline-activity
        chartPath: charts/node-http-watch-pipeline-activity
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/dignacio2015/node-http-watch-pipeline-activity'
          image.tag: '{{.DIGEST_HEX}}'
